package glue.web;

import com.github.javafaker.Faker;
import com.google.inject.Inject;
import glue.StepHelpers;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import java.util.Map;
import java.util.Optional;
import enabler.TestContext;
import org.assertj.core.api.Assertions;
import pages.CreateNewAccountPage;
import enabler.RetryUtilityStep;

public class CreateAccountSteps extends StepHelpers implements RetryUtilityStep {

  @Inject
  private CreateNewAccountPage createNewAccountPage;

  @Inject
  private Faker faker;

  @Inject
  private TestContext<String, Object> textContext;

  @When("User enters personal info: {string} and {string}")
  public void userEntersPersonalInfoAnd(String firstName, String lastName) {
    createNewAccountPage.enterPersonalInfo(firstName, lastName);
  }

  @When("User enters auto-generated personal info")
  public void userEntersAutoGeneratedPersonalInfo() {
    String firstName = Optional.ofNullable(faker.name().firstName()).get();
    String lastName = Optional.ofNullable(faker.name().lastName()).get();
    createNewAccountPage.enterPersonalInfo(firstName, lastName);
  }

  @Then("^User (checks|unchecks) the checkbox 'Sign Up for Newsletter'$")
  public void userChecksTheCheckbox(String value) {
    createNewAccountPage.signUpNewsletter(value);
  }

  @Then("User enters following sign-in info:")
  public void userEntersFollowingSignInInfo(Map<String, String> data) {
    String email = Optional.ofNullable(data.get("email"))
        .orElse(faker.internet().emailAddress());
    String fakerPassword = faker.internet().
        password(10, 12, true, true, true);
    String password = Optional.ofNullable(data.get("password"))
        .orElse(fakerPassword);
    createNewAccountPage.enterSignInInfo(email, fakerPassword, fakerPassword);
  }

  @Then("User creates an account and verifies the message: {string}")
  public void userCreatesAnAccountAndVerifiesTheMessage(String alertText) {
    boolean IsAlertMessageDisplayed = (boolean) getWithRetryStep(() -> {
          createNewAccountPage.createAnAccount();
          return createNewAccountPage.IsAlertMessageDisplayed(alertText);
        },
        MAX_RETRIES_DEFAULT,
        MAX_DELAY_SECONDS_DEFAULT
    );
    Assertions.assertThat(IsAlertMessageDisplayed)
        .as("Assert that alert is displayed")
        .isTrue();
  }
}
