package glue;

import com.github.javafaker.Faker;
import com.google.inject.Inject;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import java.util.Map;
import java.util.Optional;
import model.TestContext;
import org.assertj.core.api.Assertions;
import pages.CreateNewAccountPage;

public class CreateAccountSteps {

  @Inject
  private CreateNewAccountPage createNewAccountPage;

  @Inject
  private Faker faker;

  @Inject
  private TestContext<String, Object> textContext;

  @When("User enters personal info: {string} and {string}")
  public void userEntersPersonalInfoAnd(String firstName, String lastName) {
    createNewAccountPage.enterPersonalInfo(firstName, lastName);
  }

  @When("User enters auto-generated personal info")
  public void userEntersAutoGeneratedPersonalInfo() {
    String firstName = Optional.ofNullable(faker.name().firstName()).get();
    String lastName = Optional.ofNullable(faker.name().lastName()).get();
    createNewAccountPage.enterPersonalInfo(firstName, lastName);
  }

  @Then("^User (checks|unchecks) the checkbox 'Sign Up for Newsletter'$")
  public void userChecksTheCheckbox(String value) {
    createNewAccountPage.signUpNewsletter(value);
  }

  @Then("User enters following sign-in info:")
  public void userEntersFollowingSignInInfo(Map<String, String> data) {
    String email = Optional.ofNullable(data.get("email"))
        .orElse(faker.internet().emailAddress());
    String fakerPassword = faker.internet().
        password(10, 12, true, true, true);
    String password = Optional.ofNullable(data.get("password"))
        .orElse(fakerPassword);
    createNewAccountPage.enterSignInInfo(email, fakerPassword, fakerPassword);
  }

  @Then("User creates an account and verifies the message: {string}")
  public void userCreatesAnAccountAndVerifiesTheMessage(String alertText) {
    createNewAccountPage.createAnAccount();
    Assertions.assertThat(createNewAccountPage.IsAlertMessageDisplayed(alertText))
        .as("Assert that alert is displayed")
        .isTrue();
  }
}
